### ISSUE TITLE
path images

### ISSUE THREAD

**Issue by sandovalgus** [dtkdt100/receive_whatsapp_chat#5]
Hi!, Is there a way to return the path of the images?
I'm looking at
storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/‎IMG-X01.jpg based on the name of the image-file (msg) but in the details I see that it is in another path with other name.
![Screenshot_2022-06-07-18-17-52-448_com miui gallery](https://user-images.githubusercontent.com/4038454/172632245-0dcec60e-9905-404e-885f-6e2a864ef640.jpg)

**Comment by dtkdt100** [comment]
Are you looking for the images inside the exported chat?
I mean when you export a chat, getting all of the images that has been sent in the chat?

**Comment by sandovalgus** [comment]
I'm not sure if all the images, but I only get the message with the name of the image file
<img width="287" alt="Screen Shot 2022-06-08 at 16 12 21" src="https://user-images.githubusercontent.com/4038454/172708462-af47140c-2c8d-4c9b-8df0-443ab1410866.png">

**Comment by dtkdt100** [comment]
There is now a new version that supports saving and showing WhatsApp images.
See: https://github.com/dtkdt100/receive_whatsapp_chat/commit/4352c503f962538a29d2003cc3a4a4d4884c1c30, https://pub.dev/packages/receive_whatsapp_chat/versions/0.1.3

## Include media (currently only images are supported and Android only)

In order to include media in the exported chat, follow the steps below:
1. In WhatsApp chose INCLUDE MEDIA in the export options.
2. Call `enableReceivingChatWithMedia()` in your app.
3. To check if the message is an image message, call `isImage()` in the `MessageContent` class.
4. To get an image Widget, call `getImage()` in the `ChatContent` class, and pass the image message. It
will return ui.Image, to display it use `RawImage` class. See example below.

Note: When you choose to include media in the exported chat, WhatsApp cuts some of the media and chat, if it's too big.

For the path, in your `ChatContent` class, there is `imagePaths` parameter witch contains all of the paths. Image path will loke like this: `content://com.whatsapp.fileprovider/external_media/WhatsApp/Media/WhatsApp Images/Sent/IMG-20220609-WA0022.jpg` or `content://com.whatsapp.fileprovider/external_media/WhatsApp/Media/WhatsApp Images/Private/IMG-20220609-WA0023.jpg`.
